kubernetes/README.md
=> Add Tim Hockin's slides

fluentd/README.md
Signed-off-by: Eduardo Silva <eduardo@treasure-data.com>
=> [fluentd] add intro presentation

kubernetes/README.md
Add some useful slides about Kubernetes deep dive
=> Add more slides about Kubernetes deep dive

kubernetes/README.md
cc @idvoretskyi @caniszczyk @dankohn
=> Add my CNCF & Kubernetes Finland intro presentation

kubernetes/README.md
(ref: https://twitter.com/kubernetesonarm/status/922163339823910912)
cc @caniszczyk @dankohn @idvoretskyi
=> Add Lucas' Kubernetes' Architecture Fundamentals presentation

kubernetes/README.md
Ref: https://github.com/cncf/presentations/issues/13#issuecomment-352165204
/cc @idvoretskyi @luxas @jdumars
=> Add slides for contributing to Kubernetes

envoy/README.md
Signed-off-by: Matt Klein <mklein@lyft.com>
=> envoy: add presentations

jaeger/README.md
Signed-off-by: Yuri Shkuro <ys@uber.com>
=> Add Jaeger presentations

kubernetes/README.md
This was a presentation for SLATE in early December 2017.
=> Add Kubernetes - A Comprehensive Overview deck

kubernetes/README.md
Presented at DevOps Amsterdam in 03/2018
=> adds link to Developing on Kubernetes deck

kubernetes/README.md
=> Removing outdated formatting suggestions

kubernetes/README.md
This deck is used for the full-day Kubernetes Workshops that @jeefy and I run.
=> add k8s workshop

opa/README.md
Signed-off-by: Torin Sandall <torinsandall@gmail.com>
=> Add authz presentation from KubeCon Shanghai 2018

kubernetes/README.md
=> Update my intro to k8s & CNCF slide deck

kubernetes/README.md
Presentation on Kubernetes with various concepts inspiring everyone to switch to or learn this amazing technology
=> added new intro presentation

kubernetes/README.md
cc @dankohn @idvoretskyi @caniszczyk
=> Update my slides to the latest versions, and add one of my KubeCon talks

kubernetes/README.md
Add link to slide deck from Barcelona NCW; also added a separate paragraph for NCW's.
=> Adds slides from Barcelona New Contributor Workshop

kubernetes/README.md
Hello,
I had a talk for SIG-docs at Open Source Summit Japan so I added the slides.
=> add slides for OSSJ

linkerd/README.md
Signed-off-by: William Morgan <william@buoyant.io>
=> add Linkerd directory

prometheus/README.md
Signed-off-by: Julius Volz <julius.volz@gmail.com>
=> Update Prometheus talk link, ask for credit

README.md
Small changes, hopefully will help people get directly what they need.
=> Slight clarification of language, cleaning up of links

kubernetes/README.md
Added new slides for a presentation on Study and exam tips for the Certified Kubernetes Administrator Exam
=> Add slides for CKA Study and Exam Tips 

chinese/2021ChinaVirtual.md
=> add company for a speaker: Wang Ling

README.md, korean/README.md
Following with similar format as Chinese and Japanese
(Note: file links on README.md will be available once merged)
Co-authored-by: Sueyoung Chang <schang@cncf.io>
=> Add Korean slide files with explanation on README

people/mrbobbytables.yaml
Good example of the schema discussed in https://github.com/cncf/cncf.io/issues/757
cc @castrojo @cjyabraham
=> feat: add people folder with @mrbobbytables as an example

.github/workflows/verify.yml, cmd/main.go, cmd/verify/verify.go, go.mod, go.sum, pkg/types/types.go, pkg/verify/verify.go
As more people submit things, we want to make sure that PRs have valid data. This is a first pass at that.
=> feat: first pass at presentation.yaml validator

presentations.yaml
Add talk on Disaster Recovery for Crossplane+ArgoCD+Velero
=> Add talk on Disaster Recovery for Crossplane+ArgoCD+Velero

presentations.yaml
=> Add Amim Knabben's presentation

.github/dependabot.yml
Add Dependabot for GitHub Actions
=> Add GitHub Actions Dependabot weekly watcher

pkg/verify/verify.go, presentations.yaml
- Name now required
- Date now required
- Description now required
- Slides now required
- Fixed new error caught by the added checks
=> improve verify, fix one error

pkg/types/types.go, pkg/verify/verify.go
=> add repo field

presentations.yaml
This PR adds a presentation about the CNCF incubating Strimzi project, presented at KubeCon Europe London 2025.
=> Added presentation on Strimzi project at KubeCon EU London 2025
